# Snowflake CLI Configuration
# Minimal config file - credentials are provided via environment variables
# using the SNOWFLAKE_CONNECTIONS_<connection-name>_<key> pattern

default_connection_name = "ml_pipeline"

[connections.ml_pipeline] 