# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_data_processing.ipynb.

# %% auto 0
__all__ = ['parse_reviews']

# %% ../nbs/01_data_processing.ipynb 2
import pandas as pd
import numpy as np
from typing import Dict, Any, List
from snowflake.snowpark import Session
from snowflake.snowpark.dataframe import DataFrame
import yaml


# %% ../nbs/01_data_processing.ipynb 3
def parse_reviews(batch: Dict[str, Any]) -> Dict[str, Any]:
    """Parse reviews to extract UUID and review text from the input string.
    
    Args:
        batch: Dictionary containing 'text' and 'file_name' keys
        
    Returns:
        Dictionary with parsed UUID and review text
    """
    # Initialize empty dictionary for results
    parsed_data = {}
    
    value = batch["text"]
    # Split on the first occurrence of comma
    parts = value.split('","', 1)
    
    # Clean up the UUID (remove leading/trailing quotes)
    uuid = parts[0].strip('"')
    
    # Clean up the review text (remove trailing quote)
    review_text = parts[1].rstrip('"')
    
    # Store parsed values
    parsed_data['UUID'] = uuid
    parsed_data['REVIEW_TEXT'] = review_text
        
    return parsed_data

